### ISSUE TITLE
ToPagedResult() needs input parameter for resourceList

### ISSUE THREAD

**Issue by RobLiekens** [digipolisantwerp/web_aspnetcore#13]
resourcelist is only a placeholder for a name that must be specified at will

**Comment by erikseynaeve** [comment]
@RobLiekens 
Is dit nog relevant? Anders sluit ik het af.

**Comment by RobLiekens** [comment]
Eigenlijk wel. Zie API requirements. Als je bv. een lijst van adressen gepagineerd ophaalt, zou de structuur als volgt moeten zijn:
{
"_page":{...},
"_links":{...},
"_embedded":{
"adresses":{ => ipv adresses staat hier nu altijd 'resourceList' en er is geen optie om deze fieldname te wijzigen
....
}
}
}

**Comment by erikseynaeve** [comment]
@RobLiekens Zijn de toevoegingen aan de nieuwe versie 9.1.0 afdoende voor dit issue? Dan sluit ik dit af.

**Comment by RobLiekens** [comment]
Yes, thanks

Met vriendelijke groeten,

Rob Liekens
________________________________
