### ISSUE TITLE
useApiExtensions blocks other mime-type requests

### ISSUE THREAD

**Issue by JeroenDesmetDigipolis** [digipolisantwerp/web_aspnetcore#21]
Als er bij de startup van de api gekozen wordt, om de methode "UseApiExtensions" aan te roepen. Dan is het niet meer mogelijk om andere mime-types buiten JSON (bv. formdata) door te sturen naar de api. De requests worden nooit gerouteerd naar de api.

**Comment by erikseynaeve** [comment]
@JeroenDesmetDigipolis 
Is dit nog relevant? Anders sluit ik het af.
Indien wel relevant, zou je hiervoor dan een pull-request kunnen aanmaken?

**Comment by JeroenDesmetDigipolis** [comment]
Erik

Dit was een probleem in het project van onze stagiairs. Ik heb eerlijk gezegd geen idee of dit nog relevant is en ik zou al helemaal niet weten hoe ik het op dit moment zou moeten oplossen via een PR.

Met vriendelijke groeten,

Jeroen Desmet
Software Engineer

[cid:image001.png@01D31C30.CC904050]

Digipolis Eigen Ontwikkeling
Generaal Armstrongweg 1, 2020 Antwerpen
GSM: +32 497 89 86 63
http://www.digipolis.be<http://www.digipolis.be/>
Volg ons ook op LinkedIn<http://www.linkedin.com/company/digipolis?trk=fc_badge> - Facebook<http://www.facebook.com/Digipolis> - Twitter<http://twitter.com/#!/dgpls> - Google+<https://plus.google.com/s/Digipolis>

**Comment by erikseynaeve** [comment]
Bedankt voor de info. Ik sluit dit issue dan af omdat er voor niemand duidelijk is wat er moet gebeuren. Indien er later nog iets nodig, kan er altijd een nieuw issue geopend worden of een pull-request aangemaakt worden.
