### ISSUE TITLE
"next" page reference not given on second last page

### ISSUE THREAD

**Issue by WannesDigipolis** [digipolisantwerp/web_aspnetcore#25]
The "_links" do not show "next" page link when it is the second last page due to an error in the logic in (pages are 1-indexed):
https://github.com/digipolisantwerp/web_aspnetcore/blob/master/src/Digipolis.Web/Api/Models/PageOptionsExtensions.cs

**Comment by erikseynaeve** [comment]
fixed by pull-request from Daniel Riegelhaupt: https://github.com/digipolisantwerp/web_aspnetcore/pull/27

version: 9.0.1
