### ISSUE TITLE
SwaggerResponseDefinitions ControllerAttributes is the same as ActionAttributes

### ISSUE THREAD

**Issue by Stephan-Ghequiere** [digipolisantwerp/web_aspnetcore#29]
https://github.com/digipolisantwerp/web_aspnetcore/blob/c4109fcf240bdeb15c5a253928abe4324669c787/src/Digipolis.Web/Swagger/SwaggerResponseDefinitions.cs#L19
https://github.com/digipolisantwerp/web_aspnetcore/blob/c4109fcf240bdeb15c5a253928abe4324669c787/src/Digipolis.Web/Swagger/SwaggerResponseDefinitions.cs#L20

Wat het moet zijn:  
> ControllerAttributes = context.MethodInfo.DeclaringType.GetCustomAttributes(true).OfType<Attribute>();

**Comment by erikseynaeve** [comment]
code changed to ControllerAttributes = context.MethodInfo.DeclaringType.GetCustomAttributes(true).OfType<Attribute>();

new version 9.0.2 deployed to myget
